import next from "eslint-config-next";

const config = [
  // next-env.d.ts is generated by Next on every build and is not ours to lint.
  {ignores: [".next/**", "node_modules/**", "next-env.d.ts"]},
  ...next
];

export default config;
